### ISSUE TITLE
Add dropdown menus to section

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/gensc.github.io#44]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Each top level menu item (About, Projects, etc.) should have a drop-down menu. Just have to figure out how to do it.

**Describe alternatives you've considered**
Currently you have to click on the page to get to the subpages

**Additional context**
See also issue #43 for breadcrumbs

**Comment by dehays** [comment]
https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61

**Comment by 79-6d** [comment]
Hey, 

I just realised that [Darwin Core website](https://dwc.tdwg.org/) also has a dropdown menu (see Guides). 

If I understand correctly, they configure it in `_config.yml`, see [here](https://github.com/tdwg/dwc/blob/470dcecdbf90dba9527212c419e2cb214655fc0a/docs/_config.yml) like this:

```
navbar:
  left:
  - text: Terms
    href: terms/
  - text: Guides
    menu:
    - text: Simple Darwin Core
      href: simple/
    - text: Text
      href: text/
    - text: XML
      href: xml/
    - text: RDF
      href: rdf/
  - text: Namespace policy
    href: namespace/
  right:
  - text: GitHub
    href: https://github.com/tdwg/dwc
```

I hope it's helpful!! Thanks for your hard work!!
